name: Manual request of parcels from dogis site.

on: [workflow_dispatch]

jobs:
  parse-parcels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: node ./server/index.js
